name: Xcode - Build Only

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build project using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15

      - name: Build project
        run: |
          xcodebuild build \
          -project MonkyBook/MonkyBook.xcodeproj \
          -scheme MonkyBook \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro'

