name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15

      - name: Build for testing
        run: |
          xcodebuild build-for-testing \
          -project MonkyBook/MonkyBook.xcodeproj \
          -scheme MonkyBook \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro'
